name: Tycho Build Example CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache maven repo
      uses: actions/cache@v1
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn clean verify -PSDK -Dtycho.localArtifacts=ignore -B -V
    - name: Publish to bintray  
      uses: masofcon/upload-to-bintray-github-action@v1.0.0
      if: success() && (github.event_name == 'pull_request' || github.ref == 'master')
      with:
        source_path: ./repositories/org.example.repository.sdk/target/org.example.repository.sdk.zip
        api_user: masofcon
        api_key: ${{ secrets.BINTRAY_API_KEY }}
        repository: tycho-build-example
        package: tycho-build-example
        version: '1.6.0'
        upload_path: updates/1.6.0
        publish: ${{ github.event_name == 'pull_request' }}
        explode: 1
        override: 1
      
          
